In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as func

class LogisticModel(nn.Module):
    def __init__(self, in_dim, out_dim):
        super(LogisticModel, self).__init__()
        self.linear = nn.Linear(in_dim, out_dim)
        
    def forward(self,x):
        out = torch.sigmoid(self.linear(x))
        return out
in_dim, out_dim =1,1    
model = LogisticModel(1, 1)

In [2]:
criterion = torch.nn.BCELoss(reduction='mean')
optimiser =  torch.optim.SGD(model.parameters(), lr =0.01)

In [3]:
x_train = torch.tensor([[1.6],[2.1],[1.3],[4.8],[3.5]], dtype=torch.float).reshape(-1,1)
y_train = torch.tensor([[0],[0],[0],[1],[1]], dtype=torch.float).reshape(-1,1) 

In [4]:
epochs = 100
for epoch in range(epochs):
    inputs, labels = x_train, y_train   
    out = model(inputs)    
    optimiser.zero_grad()    
    loss = criterion(out, labels)    
    loss.backward()    
    optimiser.step()
    predicted = model.forward(x_train)    
    print('epoch{}, loss {}'.format(epoch, loss.item()))

epoch0, loss 1.0728323459625244
epoch1, loss 1.0565154552459717
epoch2, loss 1.0405337810516357
epoch3, loss 1.0248911380767822
epoch4, loss 1.009590744972229
epoch5, loss 0.9946357607841492
epoch6, loss 0.9800291061401367
epoch7, loss 0.965772807598114
epoch8, loss 0.9518685340881348
epoch9, loss 0.938317596912384
epoch10, loss 0.9251207113265991
epoch11, loss 0.9122779965400696
epoch12, loss 0.899789035320282
epoch13, loss 0.8876531720161438
epoch14, loss 0.8758689761161804
epoch15, loss 0.8644344210624695
epoch16, loss 0.8533471822738647
epoch17, loss 0.8426042795181274
epoch18, loss 0.832202136516571
epoch19, loss 0.8221370577812195
epoch20, loss 0.8124043345451355
epoch21, loss 0.8029993772506714
epoch22, loss 0.7939168214797974
epoch23, loss 0.7851510047912598
epoch24, loss 0.776695966720581
epoch25, loss 0.7685453295707703
epoch26, loss 0.7606927156448364
epoch27, loss 0.7531309723854065
epoch28, loss 0.7458532452583313
epoch29, loss 0.7388520240783691
epoch30, loss 0.7321200370

In [5]:
print(model.state_dict())

OrderedDict([('linear.weight', tensor([[0.2196]])), ('linear.bias', tensor([-0.5177]))])


In [8]:
test=torch.tensor([[0.1],[1.5],[2.3],[3.0],[6.4]])
results = model(test)
for result in results:
    if result <= 0.5:
        print(result,'false')
    else: print(result, 'true')

tensor([0.3785], grad_fn=<SelectBackward>) false
tensor([0.4531], grad_fn=<SelectBackward>) false
tensor([0.4968], grad_fn=<SelectBackward>) false
tensor([0.5352], grad_fn=<SelectBackward>) true
tensor([0.7084], grad_fn=<SelectBackward>) true
